# Setup
title:               Home
tagline:             'Prasann'
description:         'Personal Website'
url:                 https://iamprasann.github.io
baseurl:             ''
paginate:            1
permalink:           kramdown

# About/contact
author:
  name:              Prasann Viswanathan
  url:               https://iamprasann.github.io
  email:             iamprasannn@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
