# Setup
title:               Prasann
tagline:             
description:         Feel free to explore these links, and find what you were looking for!
url:                 https://iamprasann.github.io
baseurl:             ''
paginate:            1
permalink:           kramdown

# About/contact
author:
  name:              Prasann Viswanathan
  url:               https://iamprasann.github.io
  email:             iamprasannn@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
gtag: UA-146052-15